MODEL:
  ARCH: resnet50

TTA_DATA_DIR: /mnt/data0-nfs/shared-datasets/ImageNet-C
SRC_DATA_DIR: /mnt/data0-nfs/shared-datasets/ImageNet

CORRUPTION:
  DATASET: imagenetc_recur
  RECUR: 20
  NUM_CLASS: 1000
  SEVERITY:
    - 5
  TYPE:
    - motion_blur
    - snow
    - fog
    - shot_noise
    - defocus_blur
    - contrast
    - zoom_blur
    - brightness
    - frost
    - elastic_transform
    - glass_blur
    - gaussian_noise
    - pixelate
    - jpeg_compression
    - impulse_noise